### ISSUE TITLE
[FEATURE] Ability to set classes on the sidebar

### ISSUE THREAD

**Issue by EricPoul** [Tinkoff/taiga-ui#581] opened 2021-07-26 14:18 UTC
# 🚀 Feature request

### Is your feature request related to a problem?

 There is no way to add classes to the sidebar thus specific sidebar or its background can't be styled as I'd like to

### Describe the solution you'd like

 I'd like to style directly the sidebar not the inner content e.g. 
`<div *tuiSidebar="open; class: 'custom-class-1 custom-class-2'"></div>`

**Comment by alex-jss** [comment] 2021-09-09 08:45
@MarsiBarsi , @waterplea I support, the same

**Comment by waterplea** [comment] 2021-09-13 13:46
This is a duplicate of https://github.com/TinkoffCreditSystems/taiga-ui/issues/553

**Closed by waterplea** 2021-09-13 13:46 UTC
Labels: wontfix
