### ISSUE TITLE
🚀 - tuiHint with directions top-center and bottom-center

### ISSUE THREAD

**Issue by EricPoul** [Tinkoff/taiga-ui#1052] opened 2021-12-01 13:59 UTC
### Description

I'd like to have ability to use `tuiHint` with directions `top-center` and `bottom-center`(`top` and `bottom`).
I'm adding screenshot for visualisation(angular material)
![image](https://user-images.githubusercontent.com/31760529/144247383-9d701731-eaa0-4b3c-a93c-e0f0b23c64cc.png)

**Comment by waterplea** [comment] 2021-12-01 14:51
Closing as a duplicate of https://github.com/TinkoffCreditSystems/taiga-ui/issues/739 ;)

**Closed by waterplea** 2021-12-01 14:51 UTC
Labels: feature, wontfix
