### ISSUE TITLE
🐞 - tuiSelect label-placeholder have different behaviour for different values

### ISSUE THREAD

**Issue by hzsenko** [Tinkoff/taiga-ui#3853] opened 2023-03-13 13:42 UTC
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-cf2wod-cbfx4c?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Is this issue blocking you?

Non-Blocking

### Description

If initial the value of control equal null, component have label placeholder as expected.
But If I change the value of control to valid then to invalid, I want to see a label placeholder, but I have not it.
This happening cause I toggle values null to [].
Seems it's wrong behaviour. Is there way to reach that behaviour?

### Angular version

10.0.4

### Taiga UI version

2.69.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment] 2023-03-17 08:17
Closing this as by design. Empty array is not empty value. If you want to work with arrays, better choice is `MultiSelect`.

**Closed by waterplea** 2023-03-17 08:17 UTC
Labels: bug, P2
