### ISSUE TITLE
[BUG] Dialog from template or component scroll bug

### ISSUE THREAD

**Issue by MladenSijan** [Tinkoff/taiga-ui#497] opened 2021-06-21 12:54 UTC
# 🐞 Bug report

### Description
Opening dialog from template or component and scrolling while cursor is in dialog content (scrolling or swiping on specific areas inside dialog content) scrolls background content as well.

### Reproduction

https://stackblitz.com/edit/taiga-starter-scvmsa?file=src%2Fapp%2Fapp.component.html

### Expected behavior
Background content should not be scrollable while dialog is open.

### Versions

-   Browser [Chrome, Mozilla]
-   Angular [11]
-   Package [e.g. @taiga-ui/cdk@2.10.1]

**Comment by waterplea** [comment] 2022-01-21 09:59
@MladenSijan I'm unable to reproduce on Windows or Android or Chrome on Mac. If it's in Safari or iOS, it's probably a duplicate of https://github.com/Tinkoff/taiga-ui/issues/891

Feel free to reopen if it's not the case and there's a way to reproduce it not in Safari (just to emphasize, all browsers on iOS are Safari in disguise).

**Closed by waterplea** 2022-01-21 09:59 UTC
Labels: bug
