### ISSUE TITLE
tuiTabs

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#4397] opened 2023-05-05 13:59 UTC
### Discussed in https://github.com/Tinkoff/taiga-ui/discussions/4396

<div type='discussions-op-text'>

<sup>Originally posted by **erzenhaxhi** May  5, 2023</sup>
When tabs list are updated selected tab state is lost.

Playground Link: https://stackblitz.com/edit/angular-92dstq?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts

![gif](https://im.ezgif.com/tmp/ezgif-1-61db24f306.gif)

</div>

**Comment by evantrimboli** [comment] 2023-05-06 00:54
FYI, this seems related:

https://github.com/Tinkoff/taiga-ui/issues/4189

**Comment by waterplea** [comment] 2023-05-06 04:31
Yeah, that's a duplicate of it.

**Closed** 2023-05-06 04:31 UTC
Labels: bug, wontfix
