### ISSUE TITLE
🐞 - Multiselect - checkboxes not working properly..

### ISSUE THREAD

**Issue by arslan77** [Tinkoff/taiga-ui#1132] opened 2021-12-21 08:16 UTC
### Which @taiga-ui/* package(s) are the source of the bug?

core, cdk

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Description

![image](https://user-images.githubusercontent.com/12449504/146894784-9cc2c905-4372-44fd-83f5-257853cff4d6.png)

Clicking on the checkbox do nothing, it works fine on localhost but when deployed using the S3 bucket it gives a problem.  it gives this error on the console.

![image](https://user-images.githubusercontent.com/12449504/146894967-04cdeae5-cecf-4631-ac10-e3ddeb20bc90.png)

Any help in this regard will be highly appreciable. 

### Angular version

11.0

### Taiga UI version

2.1.3

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment] 2021-12-21 08:18
What do you have as value of your control? It has to be an array and it looks like you have something else.

**Comment by arslan77** [comment] 2021-12-21 09:04
It is an array, 

![image](https://user-images.githubusercontent.com/12449504/146902196-2e04b1c5-0afd-4bed-a757-de370783b210.png)

When I click second time on the dropdown then it works fine see screenshot. 

![image](https://user-images.githubusercontent.com/12449504/146902126-7209c304-e53c-497d-ac98-bdb2e9a2163b.png)

**Comment by splincode** [comment] 2021-12-21 09:14
try `FormArray` instead `FormControl([''])`

**Comment by waterplea** [comment] 2021-12-21 09:21
@splincode no, `FormArray` is wrong here. 

The error is `this.control.value.find` is not a function. Meaning there's some value, not `null`, but it's not an array because there's no `find` method.

Why do you have an array with an empty string and not an empty array?

**Comment by splincode** [comment] 2021-12-21 09:26
Oh, sorry))

**Comment by waterplea** [comment] 2022-01-12 08:53
@arslan77 can you provide a reproduction?

**Comment by waterplea** [comment] 2022-01-20 16:18
I'm closing it as I believe it's not an issue with Taiga UI code. Feel free to reopen with a reproduction.

**Closed by waterplea** 2022-01-20 16:18 UTC
Labels: wontfix
